name: dart_lang_sample_application_1
description: An application that uses a Git-hosted dependency
version: 1.0.0
homepage: https://github.com/easoncxz/dart-lang-sample-application-1


environment:
  sdk: '>=2.16.2 <3.0.0'


# dependencies:
#   path: ^1.8.0
dependencies:
  dart_lang_sample_library_1:
    git: https://github.com/easoncxz/dart-lang-sample-lib-1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
